[project]
name = "funget"
version = "1.0.11"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "funfile>=1.0.7", "funutil>=1.0.15",]

[project.scripts]
funget = "funget.script:funget"
