[project]
name = "funget"
version = "1.0.37"
description = "funget"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [ "funfile>=1.0.14",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[project.scripts]
funget = "funget.script:funget"

[tool.setuptools]
license-files = []
