[project]
name = "funget"
version = "1.0.14"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [ "funfile>=1.0.8",]

[project.scripts]
funget = "funget.script:funget"
