[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "nltget"
version = "1.1.63"
description = "Compatibility package for funget"
requires-python = ">=3.12"
license = "MIT"
dependencies = ["funget>=1.1.63"]

[project.scripts]
nltget = "funget.script:funget"
